task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-14-0
  install_script:
    - pkg install -y git gmake
    - curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_INSTALL_NO_STACK=1 sh
  script:
    - export PATH="$HOME/.ghcup/bin:$PATH"
    - cabal test --test-show-details=direct

task:
  name: OpenBSD
  compute_engine_instance:
    image_project: pg-ci-images
    # OpenBSD version should match
    # https://github.com/anarazel/pg-vm-images/blob/main/packer/openbsd.pkrvars.hcl
    image: family/pg-ci-openbsd-vanilla-7-3
    platform: openbsd
  install_script: pkg_add ghc cabal-install git
  script:
    - export CABAL_DIR=/tmp/.cabal
    - cabal update
    - cabal test --test-show-details=direct

task:
  name: NetBSD
  compute_engine_instance:
    image_project: pg-ci-images
    # NetBSD version should match
    # https://github.com/anarazel/pg-vm-images/blob/main/packer/netbsd.pkrvars.hcl
    image: family/pg-ci-netbsd-vanilla-9-3
    platform: netbsd
  install_script:
    - export PKG_PATH="http://cdn.NetBSD.org/pub/pkgsrc/packages/NetBSD/$(uname -p)/$(uname -r|cut -f '1 2' -d.)/All/"
    - pkg_add ghc cabal-install git
  script:
    - export CABAL_DIR=/tmp/.cabal
    - cabal update
    - cabal test --test-show-details=direct
