THISPKG	= fps
VERSION = 0.8
SEARCH	= -package base -Icbits
EXTRA_H_FLAGS   = -K4M #-DVERSION=$(VERSION)
#EXTRA_HBC_FLAGS = -H50M -A4M

SRCS	= \
	Data/ByteString/Base.hs \
	Data/ByteString.hs \
	Data/ByteString/Fusion.hs \
	Data/ByteString/Char8.hs \
	Data/ByteString/Lazy.hs \
	Data/ByteString/Lazy/Char8.hs \
	fpstring.c



# Here are the main rules.
include ../Makefile.common

# extra rules

# Here are any extra dependencies.

# C-files dependencies.

