#!/bin/sh

origName=$1
inName=$2
outName=$3
macros=`dirname $0`/macros.m4

if [ -z "origName" -o -z "$inName" -o -z "$outName" ] ; then
    echo "Usage: $0 original-filename input-filename output-filename"
    exit 1
fi

if [ -z "$GM4" ] ; then
    GM4=/usr/local/bin/gm4
else
    GM4=`which "$GM4"`
fi

if [ ! -x "$GM4" ] ; then
    echo "GNU m4 not found. Did you set the GM4 variable in the toplevel Makefile?"
    echo "Path to GNU m4: <$GM4>"
    exit 1
fi

exec "$GM4" -s "-D__orig_file__=\"$origName\"" "-D__TOPLEVEL_DIRECTORY__=\"`pwd`\"" "$macros" "$inName" > "$outName"
